name: create-repo-by-template
author: gendloop
description: 'Create a repository using a template'
inputs:
  token:
    description: 'Personal Token'
    required: true
    default: ${{ github.token }}
  template_owner:
    description: 'Template Owner'
    required: false
    default: 'gendloop'
  template_repo:
    description: 'Template Repo Name'
    required: true
    default: ''
  user:
    description: 'User Name'
    required: false
    default: 'gendloop'
  repo_name:
    description: 'Repo Name (e.g. MyRepo)'
    required: true
    default: ''
  repo_description:
    description: 'Repo Description'
    required: false
    default: ''
  include_all_branches:
    description: 'Include All Branches ? (true or false)'
    required: false
    default: 'false'
  is_private:
    description: 'Is Repo Private ? (true or false)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: create-repo-by-template
      shell: bash
      run: |
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.template_owner }}/${{ inputs.template_repo }}/generate \
          -d '{"owner":"${{ inputs.user }}","name":"${{ inputs.repo_name }}","description":"${{ inputs.repo_description }}","include_all_branches":${{ inputs.include_all_branches }},"private":${{ inputs.is_private }}'
