name: Template_Name

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '35 16 * * *'

jobs:
  template_name:
    runs-on: ubuntu-latest
    steps:
      - name: create-repo-by-template
        uses: gendloop/create-repo-by-template@main
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
